//
//  MVMessageRadio.h
//  MAVLink communications protocol built from ardupilotmega.xml
//
//  Created by mavgen_objc.py
//  http://qgroundcontrol.org/mavlink
//

#import "MVMessage.h"

/*!
 Class that represents a RADIO Mavlink message.

 @discussion Status generated by radio
 */
@interface MVMessageRadio : MVMessage

- (id)initWithSystemId:(uint8_t)systemId componentId:(uint8_t)componentId rssi:(uint8_t)rssi remrssi:(uint8_t)remrssi txbuf:(uint8_t)txbuf noise:(uint8_t)noise remnoise:(uint8_t)remnoise rxerrors:(uint16_t)rxerrors fixed:(uint16_t)fixed;

//! local signal strength
- (uint8_t)rssi;

//! remote signal strength
- (uint8_t)remrssi;

//! how full the tx buffer is as a percentage
- (uint8_t)txbuf;

//! background noise level
- (uint8_t)noise;

//! remote background noise level
- (uint8_t)remnoise;

//! receive errors
- (uint16_t)rxerrors;

//! count of error corrected packets
- (uint16_t)fixed;

@end
